<a href="https://colab.research.google.com/github/manjotmb20/EC3/blob/master/Letter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import os
import pandas as pd
import numpy as np
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import roc_curve,roc_auc_score
from sklearn import preprocessing
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn import tree


from sklearn.preprocessing import LabelEncoder


In [0]:
df=pd.read_csv("letter.csv")

In [5]:
df.head()

x-box  y-box  width  high  onpix  ...  x-ege  xegvy  y-ege  yegvx  class
0      2      4      4     3      2  ...      1      8      5      6     25
1      4      7      5     5      5  ...      2      9      7     10     15
2      7     10      8     7      4  ...      2      5      5     10     18
3      4      9      5     7      4  ...      3      8      0      8      7
4      6      7      8     5      4  ...      3      8      3      7      7

[5 rows x 17 columns]

In [0]:
lc=LabelEncoder()
df['class']=lc.fit_transform(df['class'])

In [0]:
y=df.iloc[:,-1]
X=df.iloc[:,:-1]

In [0]:
x_train, x_val, y_train, y_val = train_test_split(X, y,test_size=0.2,random_state=9)

In [10]:
def roc_auc_score_multiclass(actual_class, pred_class, average = "macro"):

  #creating a set of all the unique classes using the actual class list
  unique_class = set(actual_class)
  roc_auc_dict = {}
  for per_class in unique_class:
    #creating a list of all the classes except the current class 
    other_class = [x for x in unique_class if x != per_class]

    #marking the current class as 1 and all other classes as 0
    new_actual_class = [0 if x in other_class else 1 for x in actual_class]
    new_pred_class = [0 if x in other_class else 1 for x in pred_class]

    #using the sklearn metrics method to calculate the roc_auc_score
    roc_auc = roc_auc_score(new_actual_class, new_pred_class, average = average)
    roc_auc_dict[per_class] = roc_auc

  return roc_auc_dict

# assuming your already have a list of actual_class and predicted_class from the logistic regression classifier
lr_roc_auc_multiclass = roc_auc_score_multiclass(y_val, ypred3)
print(lr_roc_auc_multiclass)

NameError: ignored

In [11]:
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)
ypred=classifier.predict(x_val)
print("Accuracy score of LR",roc_auc_score_multiclass(y_val,ypred))
y_prob=classifier.predict_proba(x_val)
from sklearn.svm import SVC
classifier3=SVC(probability=True)
df=pd.DataFrame()
df['pred']=ypred
survived=pd.get_dummies(df.pred,prefix='Survived')
df=pd.concat([df,survived],axis=1)
df.drop('pred',inplace=True,axis=1)
df2=pd.DataFrame()
classifier3.fit(x_train,y_train)
ypred3=classifier3.predict(x_val)
print("Accuracy score of SVM",roc_auc_score_multiclass(y_val,ypred3))
df2['pred']=ypred3
y_prob3=classifier3.predict_proba(x_val)
survived2=pd.get_dummies(df2.pred,prefix='Surviveds')
df=pd.concat([df,survived2],axis=1)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


Accuracy score of LR {0: 0.942906101375925, 1: 0.8429146894872671, 2: 0.8578870834333895, 3: 0.8799479166666666, 4: 0.8338055472711006, 5: 0.888465168676166, 6: 0.7665294342925922, 7: 0.7257561139309535, 8: 0.9256825144983039, 9: 0.9296369469147636, 10: 0.8733900814211695, 11: 0.9179311621021465, 12: 0.9437511391765003, 13: 0.943387845549274, 14: 0.8594974642692484, 15: 0.9057701361800029, 16: 0.8388230418088982, 17: 0.8430968924389977, 18: 0.8238330710030213, 19: 0.8860235252023794, 20: 0.9217243009069731, 21: 0.921372886051077, 22: 0.9535985884670095, 23: 0.859297028768961, 24: 0.9082134069320015, 25: 0.8855331841909022}
Accuracy score of SVM {0: 0.984495409344083, 1: 0.9703469811804801, 2: 0.9480675845139944, 3: 0.96484375, 4: 0.9321751665175465, 5: 0.9711591158202412, 6: 0.9603074734653683, 7: 0.891207684886111, 8: 0.9601365028996608, 9: 0.9721402705904578, 10: 0.9585122131754255, 11: 0.9784418948926723, 12: 0.9794213277359345, 13: 0.9608726926780596, 14: 0.9417214153988013, 15: 0.

In [12]:
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
d_pred=dt.predict(x_val)
d_prob=dt.predict_proba(x_val)
accuracy_score(y_val,d_pred)
df_dt=pd.DataFrame()
df_dt['Survived_k']=d_pred
survivedt=pd.get_dummies(df_dt.Survived_k,prefix='Survivedk')
df['Survivedt_0']=survivedt['Survivedk_0']
df['Survivedt_1']=survivedt['Survivedk_1']
print("Accuracy score of DT",roc_auc_score_multiclass(y_val,d_pred))


Accuracy score of DT {0: 0.9802735318802615, 1: 0.9108735947372625, 2: 0.9149757197363858, 3: 0.9226562500000001, 4: 0.9289380157073268, 5: 0.9316237364511022, 6: 0.8900590874275085, 7: 0.9151935903351651, 8: 0.9681857971331655, 9: 0.9640398593904211, 10: 0.9179311621021465, 11: 0.9730569948186528, 12: 0.9505465107391272, 13: 0.9597017324907061, 14: 0.920628745965883, 15: 0.9449908506841358, 16: 0.9012269815046138, 17: 0.9376709705657073, 18: 0.9309413091825687, 19: 0.9395634867391207, 20: 0.947362036152706, 21: 0.9617575047445022, 22: 0.9664555750082067, 23: 0.9501383845700005, 24: 0.960101198168795, 25: 0.9348300841589432}


In [16]:
from sklearn.naive_bayes import GaussianNB
gb=GaussianNB()
gb.fit(x_train,y_train)
g_pred=gb.predict(x_val)
g_prob=gb.predict_proba(x_val)
accuracy_score(y_val,g_pred)
df_gb=pd.DataFrame()
df_gb['Survived_k']=g_pred
survivedg=pd.get_dummies(df_gb.Survived_k,prefix='Survivedg')
df['Survivedg_0']=survivedg['Survivedg_0']
df['Survivedg_1']=survivedg['Survivedg_1']
print("Accuracy score of DT",roc_auc_score_multiclass(y_val,g_pred))

Accuracy score of DT {0: 0.9360264757496375, 1: 0.8390342359974923, 2: 0.8642973398436459, 3: 0.8263020833333333, 4: 0.6567998807038472, 5: 0.8613064791133845, 6: 0.7615507714191925, 7: 0.6645958303620118, 8: 0.8992299485720537, 9: 0.8846406457729731, 10: 0.7192450037009622, 11: 0.8784418948926721, 12: 0.9263665708288501, 13: 0.8506408375887337, 14: 0.8274118257261411, 15: 0.8641152668186429, 16: 0.739133312993973, 17: 0.8261708064339643, 18: 0.6234130275815286, 19: 0.8492061362314951, 20: 0.8555350328386844, 21: 0.9011792862685586, 22: 0.9190556953714848, 23: 0.7547523227981984, 24: 0.6737235230981534, 25: 0.8060390392605158}


In [17]:
import xgboost as xgb
xgb=xgb.XGBClassifier()
xgb.fit(x_train,y_train)
x_pred=xgb.predict(x_val)
x_prob=xgb.predict_proba(x_val)
roc_auc_score_multiclass(y_val,x_pred)

{0: 0.9810555965309392,
 1: 0.9176881739612057,
 2: 0.9339463432855732,
 3: 0.9424479166666666,
 4: 0.9066694005368326,
 5: 0.9532943612227499,
 6: 0.9210936645147171,
 7: 0.8593397374050925,
 8: 0.9502680818470292,
 9: 0.9552632368805296,
 10: 0.9079940784603997,
 11: 0.9774056254626203,
 12: 0.9668771570858248,
 13: 0.9348745589217554,
 14: 0.8816562932226834,
 15: 0.9363252917507309,
 16: 0.9169247462856682,
 17: 0.9199242258452786,
 18: 0.9395349100865218,
 19: 0.9715058813005948,
 20: 0.9579260929749198,
 21: 0.9587060542086273,
 22: 0.9781841558157348,
 23: 0.9519027678512898,
 24: 0.9599715973393497,
 25: 0.9598011980562315}

In [18]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier()
forest.fit(x_train, y_train)
Y_pred = forest.predict(x_val)
print("Accuracy score of Random Forest",roc_auc_score_multiclass(y_val,Y_pred))

Accuracy score of Random Forest {0: 0.9998696558915536, 1: 0.965110747530968, 2: 0.9838442861335681, 3: 0.9884114583333333, 4: 0.9719094840441397, 5: 0.9767765801972964, 6: 0.9730345223766276, 7: 0.9504425521204749, 8: 0.9731644600065653, 9: 0.9785536846454127, 10: 0.9666913397483345, 11: 0.9891561806069579, 12: 0.9964060818795971, 13: 0.9866106130593967, 14: 0.9745274319963116, 15: 0.9748947950019334, 16: 0.9746199321893403, 17: 0.9789637815953606, 18: 0.9777138905317339, 19: 0.9929737465897401, 20: 0.9754113075027593, 21: 0.9797427387177198, 22: 0.9896118284276179, 23: 0.9838807158583441, 24: 0.9926985448199827, 25: 0.996031746031746}


In [19]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x_train, y_train)
Y_pred2 = knn.predict(x_val)
print("Accuracy score of Kneighbors",roc_auc_score_multiclass(y_val,Y_pred2))

Accuracy score of Kneighbors {0: 0.9996089676746611, 1: 0.9653706903435493, 2: 0.9862689772939512, 3: 0.9912760416666666, 4: 0.9739723133512278, 5: 0.9724531116794543, 6: 0.9665855126381442, 7: 0.9488820839800327, 8: 0.979873345004924, 9: 0.9819550451896304, 10: 0.9517579570688379, 11: 0.9959104367135455, 12: 0.9856934130609893, 13: 0.9838162197460517, 14: 0.9639810972798525, 15: 0.9525044533142205, 16: 0.9750128080405712, 17: 0.9594868147499727, 18: 0.9667649854222446, 19: 0.9823695156312895, 20: 0.9675210474719893, 21: 0.9626668318424498, 22: 0.9929013021118285, 23: 0.9721320177605522, 24: 0.9886590147416381, 25: 0.9877080413993167}


In [20]:
from sklearn.ensemble import AdaBoostClassifier
adb=AdaBoostClassifier(DecisionTreeClassifier(max_depth=1), n_estimators=100)
adb.fit(x_train,y_train)
a_pred=adb.predict(x_val)
print("Auc score", roc_auc_score_multiclass(y_val,a_pred))

Auc score {0: 0.5799708792186983, 1: 0.7341804410872745, 2: 0.845009872195096, 3: 0.8614583333333333, 4: 0.6387625509493986, 5: 0.5553069053708439, 6: 0.6056392931392931, 7: 0.730475271613742, 8: 0.7987129335813546, 9: 0.5319373012636148, 10: 0.5991857883049594, 11: 0.5969652109548482, 12: 0.5566339759758699, 13: 0.5849406067115162, 14: 0.7660068003688335, 15: 0.741654383986513, 16: 0.6028154663565873, 17: 0.6848944085786192, 18: 0.5873833921293349, 19: 0.5418131401225458, 20: 0.8505520797833473, 21: 0.5616785300731763, 22: 0.9005224860488018, 23: 0.7029256624631655, 24: 0.6432655028147111, 25: 0.8198470060886167}


In [21]:
m=np.array(df)
s=np.zeros(shape=(m.shape[0],m.shape[0]))
for i in range(m.shape[0]):
  for j in range(m.shape[0]):
    if i!=j:
      sum1=0
      for k in range(2,m.shape[1]):
        sum1=sum1+(m[i][k]*m[j][k])
      s[i][j]=sum1
w=s
d=np.zeros(shape=w.shape[0])

KeyboardInterrupt: ignored

In [0]:
for i in range(d.shape[0]):
  d[i]=np.sum(w[i],axis=0)
wnew=w/d.reshape(d.shape[0],1)
Km=wnew
Km


array([[0.        , 0.        , 0.00272975, ..., 0.00272975, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.00272975, 0.        , 0.        , ..., 0.00272975, 0.        ,
        0.        ],
       ...,
       [0.00272975, 0.        , 0.00272975, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00306748],
       [0.        , 0.        , 0.        , ..., 0.        , 0.00306748,
        0.        ]])

In [0]:
print(np.sum(Km,axis=1))
print(np.sum(Km,axis=0))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

In [0]:

m=m.dot(m.T)  
s=np.zeros(shape=(m.shape[0],m.shape[0]))
for i in range(m.shape[0]):
  for j in range(m.shape[0]):
    if i!=j:
      sum1=0
      for k in range(2,m.shape[1]):
        sum1=sum1+(m[i][k]*m[j][k])
      s[i][j]=sum1   


In [0]:
d=np.zeros(shape=w.shape[0])
w=s
for i in range(d.shape[0]):
  d[i]=np.sum(w[i],axis=0)
wnew=w/d.reshape(d.shape[0],1)  
Kc=wnew
Kc

array([[0.        , 0.00159626, 0.00159626, ..., 0.00013716, 0.00159626,
        0.00086233],
       [0.00159626, 0.        , 0.00159626, ..., 0.00013716, 0.00159626,
        0.00086233],
       [0.00159626, 0.00159626, 0.        , ..., 0.00013716, 0.00159626,
        0.00086233],
       ...,
       [0.00032536, 0.00032536, 0.00032536, ..., 0.        , 0.00032536,
        0.00125644],
       [0.00159626, 0.00159626, 0.00159626, ..., 0.00013716, 0.        ,
        0.00086233],
       [0.00122112, 0.00122112, 0.00122112, ..., 0.00075003, 0.00122112,
        0.        ]])

**Same, checking for bi-stochastic behaviour**

In [0]:
  np.sum(Kc,axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

**Generating Fg and Fo i'e the Group class matrix and Object Class matrix**

In [0]:

objclass_mat1=pd.DataFrame(y_prob,columns=['Survived','NotSurvived'])
objclass_mat2=pd.DataFrame(y_prob3,columns=['Survived','NotSurvived'])
df_t=pd.DataFrame(objclass_mat1)
Fo=np.array(df_t)
gpclass_mat=pd.DataFrame(columns=['Survived','NotSurvived'],index=['class1surv','class1notsurv','class2surv','class2notsurv'])
prob1s=np.sum(objclass_mat1.Survived)/len(objclass_mat1)
prob1ns=np.sum(objclass_mat1.NotSurvived)/len(objclass_mat1)
prob2s=np.sum(objclass_mat2.Survived)/len(objclass_mat2)
prob2ns=np.sum(objclass_mat2.NotSurvived)/len(objclass_mat2)
list1=[]
list1.append(prob1s)
list1.append(prob1ns)
list1.append(prob2s)
list1.append(prob2ns)

list2=[]
list2.append(prob1ns)
list2.append(prob1s)
list2.append(prob2ns)
list2.append(prob2s)
gpclass_mat['Survived']=list1
gpclass_mat['NotSurvived']=list2
gpclass_mat
Fg=np.array(gpclass_mat)
Fg

array([[0.38290849, 0.61709151],
       [0.61709151, 0.38290849],
       [0.37733888, 0.62266112],
       [0.62266112, 0.37733888]])

In [0]:
n=ypred.shape[1]
C=survived.shape[1]
G=survived.shape[1]*n

Yo=np.zeros(shape=(df.shape[0],C))
cal_y=np.array(df)
for i in range(Yo.shape[0]):
  Yo[i][0]=(cal_y[i][0]+cal_y[i][2])/C
for i in range(Yo.shape[0]):
  Yo[i][1]=(cal_y[i][1]+cal_y[i][3])/C

In [0]:
m=np.array(df)
Yg=np.zeros(shape=(m.shape[1],2))
c=np.sum(m,axis=0)
for i in range(Yg.shape[0]):
  if i%2==0:
    Yg[i][0]=c[i]/m.shape[0]
    Yg[i][1]=1-Yg[i][0]
  else:
    Yg[i][1]=c[i]/m.shape[0]
    Yg[i][0]=1-Yg[i][1]  
Yg

array([[0.38357588, 0.61642412],
       [0.38357588, 0.61642412],
       [0.37733888, 0.62266112],
       [0.37733888, 0.62266112]])

In [0]:
Fo_cond=True
Fg_cond=True
for i in range(Fo.shape[0]):
  if np.linalg.norm((Fo[i]), ord=1)!=1:
    Fo_cond=False
for i in range(Fg.shape[0]):
  if np.linalg.norm((Fg[i]), ord=1)!=1:
    Fo_cond=False    
print(Fo_cond)
print(Fg_cond)

True
True


In [0]:
test_dm=np.zeros(shape=(Km.shape))
test_Km=Km
for i in range(test_Km.shape[0]):
  test_dm[i]=np.sum(test_Km[i],axis=0)
Dm=np.diag(np.diag(test_dm))
print("Shape of DM",Dm.shape)
test_dc=np.zeros(shape=(Kc.shape))
test_Kc=Kc
for i in range(test_Kc.shape[0]):
  test_dc[i]=np.sum(test_Kc[i],axis=0)
Dc=np.diag(np.diag(test_dc))
print("shape of Dc",Dc.shape)

Shape of DM (962, 962)
shape of Dc (962, 962)


In [0]:
print("KHM",Km.shape)
print("KHC",Kc.shape)
print("Fo",Fo.shape)
print("Fg",Fg.shape)
print("Yo",Yo.shape)
print("Yg",Yg.shape)
print("Dm",Dm.shape)
print("Dc",Dc.shape)

KHM (962, 962)
KHC (962, 962)
Fo (962, 2)
Fg (4, 2)
Yo (962, 2)
Yg (4, 2)
Dm (962, 962)
Dc (962, 962)


In [0]:
print("KHM",Km.shape)
print("KHC",Kc.shape)
print("Fo",Fo.shape)
print("Fg",Fg.shape)
print("Yo",Yo.shape)
print("Yg",Yg.shape)
print("Dm",Dm.shape)
print("Dc",Dc.shape)

KHM (962, 962)
KHC (962, 962)
Fo (962, 2)
Fg (4, 2)
Yo (962, 2)
Yg (962, 2)
Dm (962, 962)
Dc (962, 962)


In [0]:
import sys
threshold=sys.float_info.epsilon

In [0]:
from numpy import linalg as LA

In [0]:
alpha=0.25
beta=0.35
gamma=0.35
delta=0.05
Fo_t=np.zeros(shape=Fo.shape)
Fg_t=np.zeros(shape=Fg.shape)
Fot_old=np.zeros(shape=Fo.shape)
Fo_t=Fo
Fg_t=Fg
while LA.norm((Fo_t-Fot_old),'fro')>threshold:
  Fot_old=Fo_t
  Fg_t=np.matmul((np.linalg.inv(2*delta*np.ones(shape=Dm.shape)+(alpha*Dm))),((alpha*np.matmul(Km,Fo_t))+(2*delta*Yg)))
  Fo_t=np.matmul((np.linalg.inv((alpha*Dm)+(2*beta*Dc)-(beta*np.matmul(np.identity(Kc.shape[0]),Kc))-(beta*np.matmul(np.ones(shape=Kc.shape),Kc))+(2*gamma*np.identity(Kc.shape[0])))),((alpha*np.matmul(Km,Fg_t))+(2*gamma*Yo)))

In [0]:
from sklearn.metrics import accuracy_score,roc_auc_score
result=np.zeros(shape=Fo_t.shape[0])
for i in range(Fo_t.shape[0]):
  if Fo_t[i][0]<Fo_t[i][1]:
    result[i]=1
print("Accuracy value for Ensemble model",accuracy_score(y_val,result))
print("AUC for for Ensemble model",roc_auc_score(y_val,result))
print("Accuracy value for LR",accuracy_score(y_val,ypred))
print("AUC for for LR",roc_auc_score(y_val,ypred))


Accuracy value for Ensemble model 0.8835758835758836
AUC for for Ensemble model 0.8977652312831311
Accuracy value for LR 0.8056133056133056
AUC for for LR 0.7942188294241523
